### ISSUE TITLE
Set up promote workflows

### ISSUE THREAD

**Issue by estherkim** [ampproject/cdn-configuration#1]
- [x] workflow to promote nightly
  - #29
- [x] workflow to promote other channels
  - #36
- [ ] allow PRs for manual experiment config changes
- [x] update cloudflare CDN
  - #28
- [x] install webhook pubsub publisher on this repo
- [x] trigger google CDN (connect pub/sub subscriber)
  - [x] client-side-experiments.json / `AMP_EXP`
  - [x] versions.json
- [x] tie cherrypick workflow to promote workflow?
  - #38 
  - #53 
- [ ] figure out how to do QA check for beta traffic and stable promote

**Comment by danielrozenberg** [comment]
> [ ] allow PRs for manual experiment config changes

That's basically possible and protected with various tests, right?
