### ISSUE TITLE
CDN needs HSTS and HTTPS redirect

### ISSUE THREAD

**Issue by jridgewell** [ampproject/cdn-configuration#133]
The site is accessible via HTTP, which opens up the delivered content to man-in-the-middle shenanigans (eg terrible ISPs injecting ads). Please setup [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) and an automatic HTTP->HTTPS redirect.

We can also have `ampjs.org` added to the [HSTS preload list](https://hstspreload.org/?domain=ampjs.org), so that all browsers know to connect to HTTPS without ever trying a HTTP connection.

**Comment by danielrozenberg** [comment]
Fixed on Cloudflare's side
