### ISSUE TITLE
Set up repo

### ISSUE THREAD

**Issue by estherkim** [ampproject/cdn-configuration#2]
- [x] write README.md
  - https://github.com/ampproject/cdn-configuration/pull/100
- [x] set repo as public
- [x] enable `main` branch protection rule to require PR approval to merge
- [x] PR CI checks (json validation, lint) 
  - https://github.com/ampproject/cdn-configuration/pull/13
  - https://github.com/ampproject/cdn-configuration/pull/16
  - https://github.com/ampproject/cdn-configuration/pull/22
- [x] PR check to see AMP version is live 
  - https://github.com/ampproject/cdn-configuration/pull/23
  - https://github.com/ampproject/cdn-configuration/pull/112
- [x] PR check to auto approve certain promote scenarios
  - https://github.com/ampproject/cdn-configuration/pull/75
  - https://github.com/ampproject/cdn-configuration/pull/77
- [x] PR check for code freezes
  - https://github.com/ampproject/cdn-configuration/pull/17
  - https://github.com/ampproject/cdn-configuration/pull/20
- [x] merge access for on-duty engineers
- [x] see if we need an code owners check (answer: we don't)
- [x] PR check to have 1 config change at a time
  - https://github.com/ampproject/cdn-configuration/pull/18
- [x] transfer versioning.json and client-side-experiments-config.json to this repo
  - #28 
- [x] determine what else can be transferred

**Comment by danielrozenberg** [comment]
I think we can close this issue?

**Comment by estherkim** [comment]
Almost!
